messages:
  incompatible-job: "§cYou cannot join this job because you already have an incompatible job active: "
  incompatible-job-sound: "BLOCK_NOTE_BLOCK_BASS" #block.note_block.bass
  level-decreased: "§eYour level for job §6%job% §ehas been reduced by §c%amount%§e. New level: §a%new_level%."
jobs:
  miner_f:
    on-join:
      give-permissions-per-level:
        10:
          - "group.miner_f_10"
        40:
          - "group.miner_f_40"
        50:
          - "group.miner_f_50"
        100:
          - "group.miner_100"

    on-leave:
      decrease-level: 2
      remove-permissions:
        - "group.miner_f_10"
        - "group.miner_f_40"
        - "group.miner_f_50"
        - "group.miner_100"

    incompatible-jobs:
      - "farmer"
      - "lumberjack"